name: 'Run App Smoqy, Rezan'

on: [push, pull_request]

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Install .NET 7.0
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '7.0.x'

      - name: Build
        run: dotnet build

      - name: Run Unit Tests
        run: dotnet test
